version: 2.1

executors:
  golang:
    working_directory: /go/src/github.com/mercari/terraform-provider-spinnaker
    docker:
      - image:  golang:1.14
        environment:
          GO111MODULE: "on"

commands:
  prepare-spin-config:
    description: Prepare Spinnaker spin's configuration file
    steps:
      - run:
          name: Decode SPINNAKER_SPIN_CONFIG
          command: |
            mkdir -p ~/.spin
            echo ${SPINNAKER_SPIN_CONFIG} | base64 -d > ./config

jobs:
  test:
    executor: golang
    steps:
      - checkout
      - prepare-spin-config
      - run: 
          name: Run test
          command: make test
  
  acceptance-test:
      executor: golang
      steps:
        - checkout
        - prepare-spin-config
        - run:
            name: Run acceptance test
            command: make testacc

  release:
    executor: golang
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  main:
    jobs:
      - test
      - acceptance-test
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.*)*/
